1) Importando os dados do arquivo "dados_telemetria_nave.CSV"

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('../dados_telemetria_nave.csv')
df.head()

,timestamp,temp_interna_c,temp_externa_c,integridade_estrutural,energia_capacidade_kwh,energia_carga_pct,energia_consumo_decolagem_kwh,energia_perdas_kwh,pressao_tanques_psi,status_modulos
0,2026-03-30T10:00:00,20.86,27.27,1,5000,99.00,1200,19.97,435.20,OK
1,2026-03-30T10:00:01,20.39,14.08,1,5000,98.95,1200,12.59,457.14,OK
2,2026-03-30T10:00:02,20.84,25.87,1,5000,98.90,1200,16.14,302.00,OK
3,2026-03-30T10:00:03,21.56,20.54,1,5000,98.86,1200,19.83,322.87,OK
4,2026-03-30T10:00:04,23.67,18.95,1,5000,98.81,1200,17.43,362.70,OK

2) Conhecendo os dados do arquivo dados_telemetria_nave.CSV

In [ ]:
df.shape

(500, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   timestamp                      500 non-null    object
 1   temp_interna_c                 500 non-null    float64
 2   temp_externa_c                 500 non-null    float64
 3   integridade_estrutural         500 non-null    int64
 4   energia_capacidade_kwh         500 non-null    int64
 5   energia_carga_pct              500 non-null    float64
 6   energia_consumo_decolagem_kwh  500 non-null    int64
 7   energia_perdas_kwh             500 non-null    float64
 8   pressao_tanques_psi            500 non-null    float64
 9   status_modulos                 500 non-null    object
dtypes: float64(5), int64(3), object(2)
memory usage: 39.2+ KB

In [ ]:
df.describe()

,temp_interna_c,temp_externa_c,integridade_estrutural,energia_capacidade_kwh,energia_carga_pct,energia_consumo_decolagem_kwh,energia_perdas_kwh,pressao_tanques_psi
count,500.000000,500.000000,500.000000,500.0,500.000000,500.0,500.000000,500.000000
mean,21.546820,19.977300,0.982000,5000.0,87.000000,1200.0,15.000780,372.924300
std,2.310974,5.646076,0.133084,0.0,6.949094,0.0,2.935051,48.174096
min,17.510000,10.020000,0.000000,5000.0,75.000000,1200.0,10.010000,290.510000
25%,19.555000,15.730000,1.000000,5000.0,80.997500,1200.0,12.375000,330.695000
50%,21.505000,19.705000,1.000000,5000.0,87.000000,1200.0,14.985000,371.720000
75%,23.455000,24.660000,1.000000,5000.0,93.002500,1200.0,17.520000,414.235000
max,25.480000,29.980000,1.000000,5000.0,99.000000,1200.0,19.970000,459.810000

3.